### ISSUE TITLE
Update to openssl v3 please

### ISSUE THREAD

**Issue by dimaslanjaka** [areful/NdkUseOpenssl#2]
can you update to v3 ? iam using windows, hard to build openssl :( consider using prebuilt like this repo

**Comment by areful** [comment]
I see some projects have implement v3 version, like this: https://github.com/217heidai/openssl_for_android,
maybe it can help you?

**Comment by areful** [comment]
Seems easy, let me try later.

**Comment by dimaslanjaka** [comment]
> I see some projects have implement v3 version, like this: https://github.com/217heidai/openssl_for_android, maybe it can help you?

its `.a` files, how to include them into gradle ?

**Comment by areful** [comment]
> > I see some projects have implement v3 version, like this: https://github.com/217heidai/openssl_for_android, maybe it can help you?
> 
> its `.a` files, how to include them into gradle ?

Can't use .a library directly in Android apps, U must compile it to .so library files first.

**Comment by areful** [comment]
Upgraded openssl to v3.3.0-dev.

**Comment by dimaslanjaka** [comment]
emm are this warnings okay ? in CI this warnings made the build step failure, but in local work to bundle.

there no modification for cmakelist.txt ? 

i bundled this with android sdk api 34 (cupcake), i think uses ndk v26.xxxx, kotlin 1.9.21, AGP 8.3, openjdk-19

![image](https://github.com/areful/NdkUseOpenssl/assets/12471057/b36ade5c-0eed-4ac2-8299-8292f18a5cf6)

**Comment by areful** [comment]
> emm are this warnings okay ? in CI this warnings made the build step failure, but in local work to bundle.
> 
> there no modification for cmakelist.txt ?
> 
> i bundled this with android sdk api 34 (cupcake), i think uses ndk v26.xxxx, kotlin 1.9.21, AGP 8.3, openjdk-19
> 
> ![image](https://private-user-images.githubusercontent.com/12471057/313438069-b36ade5c-0eed-4ac2-8299-8292f18a5cf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MjQzMjgsIm5iZiI6MTcxMDcyNDAyOCwicGF0aCI6Ii8xMjQ3MTA1Ny8zMTM0MzgwNjktYjM2YWRlNWMtMGVlZC00YWMyLTgyOTktODI5MmYxOGE1Y2Y2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDAxMDcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MWZmYjdkMjQ2NmVkYzU1M2E2NjAzZDZmMjg0NWJkNDJkNGU5ZGZkOGU4NjY2YzZiMDczMmYyYWRkOWQwMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FEbibAJllg84plw6v-DjGfrIuR1wtFyeZhYF4nUz974)

These are just compile warnings, not compile  error, means some codes are deprecated, we should use newer codes to replace them, but current implementation still works. Not enough time to modify them, sorry.

I think U can simply modify the CMakeLists.txt or app's gradle to avoid compile errors, like '-w' option for comipling cpp code.

**Comment by dimaslanjaka** [comment]
trying to suppress then, thanks for update
